skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
prediction_market_solana_anchor = "7PBhPD5n3Qe18BoFR4uiRNVTCoqz3RYh9mypf6CC3tww"

[programs.localnet]
prediction_market_solana_anchor = "6pUx6pwYTVo5Aa2E217K4mRyRMa7jujHYvApgeVpSJBn"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
