[workspace]
resolver = "2"
members = [
    "crates/*",
    "services/*"
]

[workspace.dependencies]
actix-web = "4"
actix-cors = "0.7"
actix-ws = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# Use SQLx 0.6 to perfectly align with solana-sdk 1.18.0 crypto dependencies
sqlx = { version = "0.6", default-features = false, features = ["postgres", "runtime-tokio-rustls", "time", "macros"] }
rdkafka = "0.36"
solana-sdk = "~1.18"
solana-client = "~1.18"
anchor-client = "0.30.1"
dotenvy = "0.15"
async-trait = "0.1"
